# Generated by Django 5.0.4 on 2024-05-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
