# Generated by Django 5.0.3 on 2024-03-27 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTokens',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('platform', models.IntegerField()),
                ('invitee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_auth_tokens', to='user.user')),
            ],
            bases=('common.basemodel',),
        ),
    ]
