# Generated by Django 5.0.3 on 2024-03-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_authtokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authtokens',
            old_name='invitee',
            new_name='inviter',
        ),
    ]
