# Generated by Django 5.0.3 on 2024-04-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_token_expiry_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokens',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
