# Generated by Django 5.0.3 on 2024-03-28 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('user', '0003_rename_invitee_authtokens_inviter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_invitee_notified', models.BooleanField(blank=True, default=False, null=True)),
                ('is_inviter_notified', models.BooleanField(blank=True, default=False, null=True)),
                ('invite_status', models.IntegerField(blank=True, null=True)),
                ('reschedule_invite_id', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('is_expired', models.BooleanField(blank=True, default=False, null=True)),
                ('invitees_count', models.IntegerField(blank=True, default=0, null=True)),
                ('invitees_emails', models.TextField(blank=True, null=True)),
                ('inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inviter', to='user.user')),
            ],
            bases=('common.basemodel',),
        ),
    ]
