# Generated by Django 5.0.3 on 2024-03-29 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('invite', '0002_invitation_invitation_link_and_more'),
        ('user', '0003_rename_invitee_authtokens_inviter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('platform', models.IntegerField(blank=True, null=True)),
                ('duration_in_minutes', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
            bases=('common.basemodel',),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to='user.user'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invite_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='invite.invite'),
        ),
    ]
