# Generated by Django 5.0.3 on 2024-04-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0004_remove_invitation_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='time',
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitation_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
