# Generated by Django 5.0.3 on 2024-04-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0005_remove_invitation_date_remove_invitation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitation_unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
